### ISSUE TITLE
inconsistent description in ReadMe.

### ISSUE THREAD

**Issue by hyang428** [sdimi/Step2heart#1]
The input vector of activity for the pre-training task is a 3D tensor of dimensions **X =  [samples, timesteps, features]** while the output heart rate is an 1D vector of  **Y = [samples].** In particular, in /data we provide **X = [1, 512, 34] and y = [512].** The outcomes for transfer learning in data/fitness_test are in an 2D vector of [samples, features].

So, here Y = [samples] or [timesteps] ?

**Comment by sdimi** [comment]
hi @hyang428, in this sample we provide in this repo, the Y vector for the _upstream_ task is y = [512] which corresponds to 512 samples for every one of the timestamps of the input vector X. Since we provide just one data point, you can skip grouping the window-level activations to user-level, as currently shown in 05_transfer_learning.

The input vector for the _downstream_ task, in this case, will be a 2D vector of [1, latent_size]. The output vector in downstream is again a 1D [512] vector.

I hope this helps.

**Comment by sdimi** [comment]
On second thought, I should have shared only *one* (not 512) values of the upstream y. I just updated the Y_windows_one_user_sample.npy file to capture that. 

Essentially every datapoint (which is a 512-long window) should correspond to a _single_ future heart rate. And since I shared just one input window, the output is a single value.

**Comment by hyang428** [comment]
Thanks for the clarification. best wishes~
